tesutome/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'site#index'

  get 'site/about' => 'site#about'
  match 'site/contact' => 'site#contact', via: [:get, :post]

  match 'project/create' => 'project#create', via: [:get, :post]
  get 'project/:id/view' => 'project#view'
  get 'project/search/user/:project_id/:name' => 'project#search_user'
  post 'project/invite' => 'project#invite'
  put 'project/invite/cancel' => 'project#invite_cancel'
  put 'project/invite/accept' => 'project#invite_accept'
  put 'project/invite/reject' => 'project#invite_reject'

  post 'image/upload' => 'image#upload'

end

tesutome/app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user

  has_many :project_members

  validates :user_id, numericality: {only_integer: true}, allow_nil: false
  validates :title, uniqueness: true, allow_nil: false

  def owner
    return self.user
  end

  def members
    all_members = []
    all_members << self.owner
    project_members = self.project_members.where(status: ProjectMember::ACCEPTED).all
    if project_members.present? && project_members.count > 0
      project_members.each do |project_member|
        all_members << project_member.user
      end
    end
    return all_members
  end

  def invitation_pending_members
    return self.project_members.where(status: ProjectMember::REQUESTING).all
  end
end

tesutome/app/models/project_member.rb
class ProjectMember < ActiveRecord::Base
  belongs_to :user
  belongs_to :project

  validates :user_id, :project_id, :role, :status, numericality: {only_integer: true}, allow_nil: false

  ROLE_IDS = {
    (DEVELOPER = 10) => "Developer",
    (TESTER    = 20) => "Tester",
    (WATCHER   = 30) => "Watcher"
  }

  STATUS_IDS = {
    (REQUESTING = 10) => "Invitation requesting",
    (ACCEPTED   = 20) => "Invitation accepted",
    (CANCELED   = 30) => "Invitation canceled",
    (REJECTED   = 40) => "Invitation rejected"
  }

  def role_name
    ROLE_IDS[self.role]
  end

end

tesutome/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :project_members

  def user_name
    return self.email.split('@').first
  end

  def projects
    result = Project.all.where(user_id: self.id)
    self.project_members.each do |project_member|
      result << project_member.project if project_member.status == ProjectMember::ACCEPTED
    end
    return result
  end
end

tesutome/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate_user!
end

tesutome/app/controllers/image_controller.rb
class ImageController < ApplicationController

  require 'net/http'
  require 'net/https'
  require 'open-uri'
  require 'json'
  require 'base64'

  API_URI = URI.parse('https://api.imgur.com/3/')
  API_PUBLIC_KEY = 'Client-ID cdafb7066b5dcd1'

  ENDPOINTS = {
    :image => 'image',
  }

  def upload
    result = nil
    img = File.open(params[:image].tempfile, "rb") {|io| io.read}
    params = {
      :image => Base64.encode64(img)
    }
    request = Net::HTTP::Post.new(API_URI.request_uri + ENDPOINTS[:image])
    request.set_form_data(params)
    request.add_field('Authorization', API_PUBLIC_KEY)
    response = web_client.request(request)
    result = JSON.parse(response.body) #['data']['link']
    respond_to do |format|
      format.html
      format.json { render json: {:status => result.present? ? result['success'] : false, :image_url => result.present? ? result['data']['link'] : nil}}
    end
  end

  private

  def web_client
    http = Net::HTTP.new(API_URI.host, API_URI.port)
    http.use_ssl = true
    http.verify_mode = OpenSSL::SSL::VERIFY_NONE
    http
  end
end

tesutome/app/controllers/project_controller.rb
class ProjectController < ApplicationController
  def create
    if params[:title].present?
      project = Project.create(title: params[:title], description: params[:description], icon_url: params[:icon_url], user_id: current_user.id)
      redirect_to :action => 'view', :id => project.id
    else
      @project = Project.new
      render :new
    end
  end

  def view
    @project = Project.find(params[:id])
    render :view
  end

  def search_user
    current_project = Project.find(params[:project_id])
    project_members = current_project.members
    project_invitation_pending_members = current_project.invitation_pending_members.pluck(:user_id)
    all_users = User.where("email like ?", "%#{params[:name]}%").all
    @search_users = []
    all_users.each do |user|
      unless project_members.include?(user) || project_invitation_pending_members.include?(user.id)
        @search_users << user
      end
    end
    @current_project_id = params[:project_id]
    respond_to do |format|
      format.html
      format.js {render layout: false}
    end
  end

  def invite
    project_id = params[:project_id]
    user_id = params[:user_id]
    role = params[:role]
    result = false
    project_member = ProjectMember.where(:project_id => project_id, :user_id => user_id).all.first
    if project_member.present?
      if project_member.status == ProjectMember::REQUESTING || project_member.status == ProjectMember::ACCEPTED
        result = false
      else
        project_member.update_attributes(:status => ProjectMember::REQUESTING, :role => role)
        project_member.save!
        result = true
      end
    else
      project_member = ProjectMember.create(:project_id => project_id, :user_id => user_id, :role => role, :status => ProjectMember::REQUESTING)
      result = true
    end
    respond_to do |format|
      format.html
      format.json {
        render json: {
          :status => result,
          :invitation_pending_member => {
            :id => project_member.id,
            :project_id => project_member.project_id,
            :user_name => project_member.user.user_name,
            :role_name => project_member.role_name
          }
        }
      }
    end
  end

  def invite_cancel
    respond_to do |format|
      format.html
      format.json { render json: {:status => invitation_process(params[:invitation_id], ProjectMember::CANCELED)}}
    end
  end

  def invite_accept
    respond_to do |format|
      format.html
      format.json { render json: {:status => invitation_process(params[:invitation_id], ProjectMember::ACCEPTED)}}
    end
  end

  def invite_reject
    respond_to do |format|
      format.html
      format.json { render json: {:status => invitation_process(params[:invitation_id], ProjectMember::REJECTED)}}
    end
  end

  private

  def invitation_process(invitation_id, status)
    return false if invitation_id.blank? || status.blank?
    invitation = ProjectMember.find(params[:invitation_id])
    if invitation.present? && invitation.status == ProjectMember::REQUESTING
      invitation.update_attribute(:status, status)
      invitation.save!
      return true
    end
    return false
  end
end

tesutome/app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_filter :authenticate_user!, except: [:about, :contact]

  def index
    @projects = current_user.projects.sort_by{ |e| e[:updated_at] }
    @projects = @projects.reverse
    @invitation_messages = ProjectMember.where(:user_id => current_user.id, :status => ProjectMember::REQUESTING)
    render :index
  end

  def about
    render :about
  end

  def contact
    render :contact
  end
end

tesutome/app/helpers/application_helper.rb
module ApplicationHelper
end

tesutome/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= t('app_name') %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.11.1/jquery.validate.min.js"></script>
  <script type="text/javascript">
    function showFlashMessageLabel(element) {
      setTimeout(function() {
        element.setAttribute("style", "display: none;");
      }, 5000);
    }
  </script>
</head>
<body>

  <div class="navbar navbar-default" style="border-radius: 0px;">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#header-bar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a href="/" class="navbar-brand"><%= t('app_name') %></a>
        </div>

        <div class="collapse navbar-collapse" id="header-bar-collapse">
          <% if user_signed_in? %>
          <ul class="nav navbar-nav navbar-right">
            <li><a href="/site/about"><%= t('about') %></a></li>
            <li><a href="/site/contact"><%= t('contact') %></a></li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= current_user.user_name %><span class="caret"></span></a>
              <ul class="dropdown-menu" role="menu">
                <li><%= link_to(t('edit_profile'), edit_user_registration_path) %></li>
                <li class="divider"></li>
                <li><%= link_to(t('sign_out'), destroy_user_session_path, :method => :delete) %></li>
              </ul>
            </li>
          </ul>
          <% else %>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="/site/about"><%= t('about') %></a></li>
              <li><a href="/site/contact"><%= t('contact') %></a></li>
              <li><a href="/"><%= t('sign_in') %></a></li>
              <li><a href="/users/sign_up"><%= t('sign_up') %></a></li>
            </ul>
          <% end %>
        </div>
      </div>
  </div>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

tesutome/app/views/project/_search_user.html.erb
<br/>
<% if @search_users.present? && @search_users.count > 0 %>
  <br/>
  <table class="table table-striped table-hover "><tbody>
    <% @search_users.each do |search_user| %>
      <tr>
        <div id="search_user_item_<%= search_user.id %>" class="row">
          <div class="col-md-5">
            <div><a href="/">
              <h5 style="font-size: 13pt; font-weight: bold;"><%= search_user.user_name %></h5>
            </a></div>
            <div><p>(<%= search_user.email %>)</p></div>
          </div>
          <div class="col-md-7" style="height: 100%; position: relative; top: 50%;">
            <p>Invite this user to join project as </p>
            <p>
              <button class="btn btn-success btn-sm" onclick="onClickInvitationButton('<%= @current_project_id %>', '<%= search_user.id %>', '10');"><%= t('project.developer') %></button>
              <button class="btn btn-success btn-sm" onclick="onClickInvitationButton('<%= @current_project_id %>', '<%= search_user.id %>', '20');"><%= t('project.tester') %></button>
              <button class="btn btn-success btn-sm" onclick="onClickInvitationButton('<%= @current_project_id %>', '<%= search_user.id %>', '30');"><%= t('project.watcher') %></button>
            </p>
          </div>
        </div>
        <hr id="search_user_line_<%= search_user.id %>">
      </tr>
    <% end %>
  </tbody></table>
<% else %>
  <br/>
  <div class="well">
    No users found.
  </di>
<% end %>
<script type="text/javascript">
 function onClickInvitationButton(currentProjectId, userId, memberType) {
   var successLabel = document.getElementById('user_invitation_success');
   var errorLabel = document.getElementById('user_invitation_error');
   successLabel.setAttribute("style", "display: none;");
   errorLabel.setAttribute("style", "display: none;");
   // Error
   if (!currentProjectId || !userId || !memberType) {
     errorLabel.setAttribute("style", "display: true;");
     return;
   }
   $.ajax({
     type: 'POST',
     url: '/project/invite',
     data: {project_id: currentProjectId, user_id: userId, role: memberType},
     dataType: 'json',
     success: function(data) {
       if (data.status) {
         var item = document.getElementById('search_user_item_' + userId);
         item.parentNode.removeChild(item);
         var line = document.getElementById('search_user_line_' + userId);
         line.parentNode.removeChild(line);
         successLabel.setAttribute("style", "display: true;");
         showFlashMessageLabel(successLabel);
         var emptyLabel = document.getElementById('project_invitation_pending_members_empty_label');
         if (emptyLabel != null) {
           emptyLabel.setAttribute("style", "display: none;");
         }
         var invitationElement =
          '<div id="project_user_invitation_row_' + data.invitation_pending_member.id + '" class="row">' +
            '<div class="col-md-5">' +
              '<a href="/" style="font-weight: bold;">' + data.invitation_pending_member.user_name + '</a> has been invited to join project as <span style="font-weight: bold;">' + data.invitation_pending_member.role_name + '</span>' +
            '</div>' +
            '<div class="col-md-7" style="height: 100%; position: relative; top: 50%; transform: translateY(-25%);">' +
              '<button class="btn btn-danger btn-sm pull-left" onclick="onClickInvitationCancelButton(' + data.invitation_pending_member.id + ')"><%= t('cancel') %></button>' +
            '</div>' +
          '</div>' +
          '<hr id="project_user_invitation_line_' + data.invitation_pending_member.id + '">';
         $("#project_invitation_pending_list").append(invitationElement);
       } else {
         errorLabel.setAttribute("style", "display: true;");
         showFlashMessageLabel(errorLabel);
       }
     },
     error: function(error) {
       errorLabel.setAttribute("style", "display: true;");
       showFlashMessageLabel(errorLabel);
     }
   });
 }
</script>

tesutome/app/views/project/new.html.erb
<div class="jumbotron">
  <div class="container">
    <h2><%= t('project.create') %></h2>
    <br/>

    <%= form_for @project, url: project_create_path, method: :post, html: {id: 'project_create_form', class: 'form-group'} do |f| %>
      <%= label_tag t('project.title'), nil, style: 'font-size: 16pt' %> (max 128 characters)
      <%= f.text_field :title, class: 'form-control', id: 'title', name: 'title' %>
      <br/>
      <%= label_tag t('project.description'), nil, style: 'font-size: 16pt' %> (max 256 characters)
      <%= f.text_area :description, class: 'form-control', rows: 5, id: 'description', name: 'description' %>
      <br/>
      <%= label_tag t('project.icon'), nil, style: 'font-size: 16pt' %>
      <div class="row">
        <div class="col-md-2" style="margin: 10px 0 10px 0;">
          <img id="project_icon_view" src="http://teamhoppi.com/img/no_image_thumbnails.png" class="pull-left" style="width: 150px; height: 150px;" />
          <%= f.hidden_field :icon_url, id: 'icon_url', name: 'icon_url', value: 'http://teamhoppi.com/img/no_image_thumbnails.png' %>
        </div>
        <div class="col-md-10">
           <p style="margin-left: -15px; margin-top: 50px; padding-left: 0px;">
             <div class="input-group">
                <span class="input-group-btn">
                  <span class="btn btn-primary btn-file">
                    <input id="project_icon_input_file" name="project_icon_input_file" type="file" accept="image/*">
                  </span>
                </span>
                <input type="text" class="form-control" readonly>
             </div>
           </p>
        </div>
      </div>
      <div id="icon_image_upload_progress_bar" style="display: none;" class="progress progress-striped active">
  			<div class="progress-bar progress-bar-success" style="width: 100%"></div>
  		</div>
      <br/>
      <%= f.submit t('project.create'), class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

<script type="text/javascript">
$(document).ready(function() {
  $("#project_create_form").validate({
    rules: {
      title: {
        required: true,
        minlength: 3,
        maxlength: 128
      },
      description: {
        maxlength: 256
      }
    },
    messages: {
      title: {
        required: "No name, no project",
        minlength: "Project title has at least 3 characters",
        maxlength: "Project title has max 128 characters",
      },
      description: {
        maxlength: "Project description has max 256 characters"
      }
    }
  });
})

  $("#project_icon_input_file").change(function() {
    var input = $(this), numFiles = input.get(0).files ? input.get(0).files.length : 1, label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
    input.trigger('fileselect', [numFiles, label]);

    if (input.get(0).files.length > 0) {
      var imageData = new FormData();
      $.each(input.get(0).files, function(key, value) {
          imageData.append("image", value);
      });

      var iconImageUploadProgressBar = document.getElementById("icon_image_upload_progress_bar");
      iconImageUploadProgressBar.setAttribute("style", "display: true;");

      $.ajax({
          url: "/image/upload",
          type: "POST",
          data: imageData,
          dataType: 'json',
          contentType: false,
          processData:false,
          cache: false,
          success: function(data) {
            // success
            iconImageUploadProgressBar.setAttribute("style", "display: none;");
            if (data.status && data.image_url) {
              var projectIconView = document.getElementById('project_icon_view');
              projectIconView.setAttribute("src", data.image_url);
              var projectIconUrl = document.getElementById('icon_url');
              projectIconUrl.setAttribute("value", data.image_url);
            } else {
              alert("There's something wrong!");
            }
          },
          error: function(error){
            // error
            iconImageUploadProgressBar.setAttribute("style", "display: none;");
            alert("There's something wrong!");
          }
      });
    }
  });

  $('.btn-file :file').on('fileselect', function(event, numFiles, label) {
    var input = $(this).parents('.input-group').find(':text'),
        log = numFiles > 1 ? numFiles + ' files selected' : '  ' + label;
    if( input.length ) {
        input.val(log);
    } else {
        if( log ) alert(log);
    }
  });
</script>

tesutome/app/views/project/search_user.js.erb
$("#project_search_user_list").empty().append("<%= escape_javascript(render 'search_user') %>");

tesutome/app/views/project/view.html.erb
<%= link_to t('back'), :back %>

<div class="input-group">
  <span class="input-group-btn">
    <h2 class="pull-left" style="font-weight: bold;"><%= @project.title %></h2>
  </span>
</div>
<br/>
<ul class="nav nav-tabs">
  <li class="active"><a href="#detail" data-toggle="tab" aria-expanded="true"><%= t('project.details') %></a></li>
  <li class=""><a href="#invitation" data-toggle="tab" aria-expanded="false"><%= t('project.invitation') %></a></li>
  <li class=""><a href="#android" data-toggle="tab" aria-expanded="false"><%= t('project.android') %></a></li>
  <li class=""><a href="#ios" data-toggle="tab" aria-expanded="false"><%= t('project.ios') %></a></li>
</ul>

<div class="tab-content">
  <!-- Project Details tab section - START -->
  <div class="tab-pane fade active in" id="detail">
    <br/>
    <div class="container">
      <div class="row">
        <div class="col-md-1" style="margin: 0 0 5px 0;">
          <img src="<%= @project.icon_url %>" class="thumbnail pull-left" style="width: 100px; height: 100px;" />
        </div>
        <div class="col-md-11" style="margin: 0 0 -50px 0;">
          <ul>
            <li><p>Owner: <%= @project.owner.user_name %></p></li>
            <li><p>Description: <%= @project.description.present? ? @project.description : "No description" %></p></li>
            <li><p>Created at: <%= @project.created_at %></p></li>
            <li><p>Members: <% @project.members.each do |member| %><a href="/"><%= member.user_name %>, <% end %></a></p></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

  <!-- Project Invitations tab section - START -->
  <div class="tab-pane fade" id="invitation">
    <br/>
    <div id="user_invitation_success" class="alert alert-dismissible alert-success" style="display: none;">
      <%= t('success') %>
    </div>
    <div id="user_invitation_error" class="alert alert-dismissible alert-danger" style="display: none;">
      <%= t('fail') %>
    </div>
    <div class="container">
      <div class="form-group">
        <label class="control-label">Search Users</label>
        <div class="input-group" style="width: 50%;">
          <input id="user-search-textbox" type="text" class="form-control">
          <span class="input-group-btn">
            <button id="user-search-button" class="btn btn-info" type="button">Search</button>
          </span>
        </div>
        <p id="user-search-error-label" class="text-danger" style="display: none;">No name, no search!</p>
        <div id="project_search_user_list">
          <!-- search user list -->
        </div>
        <br/>
        <label class="control-label">Invitation Sent Users</label>
        <div id="project_invitation_pending_list">
          <br/>
          <table class="table table-striped table-hover "><tbody>
            <% if @project.present? && @project.invitation_pending_members.count > 0 %>
              <% @project.invitation_pending_members.each do |pending_user| %>
                <tr>
                  <div id="project_user_invitation_row_<%= pending_user.id %>" class="row">
                    <div class="col-md-5">
                      <%= t('project.invitation_message',
                            user: content_tag(:a, pending_user.user.user_name, href: '/', style: 'font-weight: bold;'),
                            role: content_tag(:span, pending_user.role_name, style: 'font-weight: bold;')).html_safe %>
                    </div>
                    <div class="col-md-7" style="height: 100%; position: relative; top: 50%; transform: translateY(-25%);">
                      <button class="btn btn-danger btn-sm pull-left" onclick="onClickInvitationCancelButton('<%= pending_user.id %>')"><%= t('cancel') %></button>
                    </div>
                  </div>
                  <hr id="project_user_invitation_line_<%= pending_user.id %>">
                </tr>
              <% end %>
            <% else %>
              <div id="project_invitation_pending_members_empty_label" class="well">
                No users found.
              </div>
            <% end %>
          </tbody></table>
        </div>
      </div>
    </div>
  </div>

  <!-- Project Android files tab section - START -->
  <div class="tab-pane fade" id="android">
    <br/>
    <div class="container">
    </div>
  </div>

  <!-- Project iOS files tab section - START -->
  <div class="tab-pane fade" id="ios">
    <br/>
    <div class="container">
    </div>
  </div>
</div>

<script type="text/javascript">
  var userSearchErrorLabel = document.getElementById('user-search-error-label');
  $("#user-search-button").click(function() {
    var searchUserName = document.getElementById('user-search-textbox').value;
    if (searchUserName == "") {
      userSearchErrorLabel.setAttribute("style", "display: true;");
      $("#project_search_user_list").empty();
      return;
    }
    userSearchErrorLabel.setAttribute("style", "display: none;");
    $.ajax({
      type: 'GET',
      url: "/project/search/user/" + <%= @project.id %> + "/" + searchUserName,
      dataType: 'script'
    });
  })

  function onClickInvitationCancelButton(invitation_id) {
    var successLabel = document.getElementById('user_invitation_success');
    var errorLabel = document.getElementById('user_invitation_error');
    successLabel.setAttribute("style", "display: none;");
    errorLabel.setAttribute("style", "display: none;");
    $.ajax({
      type: 'PUT',
      url: '/project/invite/cancel',
      data: {invitation_id: invitation_id},
      dataType: 'json',
      success: function(data) {
        if (data.status) {
          var item = document.getElementById('project_user_invitation_row_' + invitation_id);
          item.parentNode.removeChild(item);
          var line = document.getElementById('project_user_invitation_line_' + invitation_id);
          line.parentNode.removeChild(line);
          successLabel.setAttribute("style", "display: true;");
          showFlashMessageLabel(successLabel);
        } else {
          errorLabel.setAttribute("style", "display: true;");
          showFlashMessageLabel(errorLabel);
        }
      },
      error: function(error) {
        errorLabel.setAttribute("style", "display: true;");
        showFlashMessageLabel(errorLabel);
      }
    });
  }

</script>

tesutome/app/views/site/contact.html.erb
<%= form_tag({controller: 'site', action: 'contact'}, method: 'post', id: 'contact_form', class: 'form-group') do %>
  <%= label_tag 'Name', nil, style: 'font-size: 16pt' %>
  <%= text_field_tag 'name', nil, placeholder: 'Your name...', class: 'form-control', maxlength: 128 %>
  <br/>
  <%= label_tag 'Email', nil, style: 'font-size: 16pt' %>
  <%= text_field_tag 'email', nil, placeholder: 'Email Address...', class: 'form-control', maxlength: 64 %>
  <br/>
  <%= label_tag 'Comment', nil, style: 'font-size: 16pt' %>
  <%= text_area_tag 'comment', nil, placeholder: 'Comment...', class: 'form-control', rows: 5, maxlength: 512 %>
  <br/>
  <%= submit_tag 'Submit', class: 'btn btn-primary' %>
<% end %>

<script type="text/javascript">
$(document).ready(function() {
  $("#contact_form").validate({
    rules: {
      name: {
        required: true,
        minlength: 5,
      },
      email: {
        required: true,
        email: true
      },
      comment: {
        required: true,
        minlength: 10
      }
    },
    messages: {
      name: {
        required: "Come on, you have a name, don't you?",
        minlength: "Your name must consist of at least 5 characters"
      },
      email: {
        required: "No email, no comment"
      },
      comment: {
        required: "Um...yea, you have to write something to send this form",
				minlength: "That's all? really?"
      }
    }
  });
})

</script>

tesutome/app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>